Merge release/1.0 branch as a squash commit
Squashed commit of the following:

commit 83d81e01c88c90949fd20f04551f879995fc9a81
Author: Richard Holme <richard.holme@arris.com>
Date:   Wed Apr 24 10:35:54 2019 +0100

    Factory reset example confusingly had self:: in Host rather than EndpointID

commit 58080503f291637e2394aedab21570203046e637
Author: Richard Holme <richard.holme@arris.com>
Date:   Tue Apr 23 10:13:12 2019 +0100

    Updated Quick start guide with autotools dependency

commit edc4546f630232023ad8a322d1f13709b64d7a32
Author: Richard Holme <richard.holme@arris.com>
Date:   Wed Apr 17 20:31:30 2019 +0100

    OBUSPA-12: QUICK_START_GUIDE.md needs instructions for protobuf-c directory

    When building under Ubuntu 18, the following error occurs:
    src/core/main.c:47:35: fatal error: protobuf-c/protobuf-c.h: No such
    file or directory
    The fix is to an an extra include path to Makefile.am.

commit aa736efb492a3cf86c6689fd8e3fee81381a8ab0
Author: Richard Holme <richard.holme@arris.com>
Date:   Thu Mar 21 14:14:13 2019 +0000

    Added BBF copyright to license

commit c623a78857bd610928d38a2404c80684cb0a84cf
Author: Richard Holme <richard.holme@arris.com>
Date:   Thu Mar 21 12:44:00 2019 +0000

    Better README

commit 24ebf487e170cfd2f67f6a0ccbc1127e26c3b873
Author: Richard Holme <richard.holme@arris.com>
Date:   Thu Mar 21 12:39:09 2019 +0000

    Changed readme to description of repository code

commit 9a4035bac6b52bccddaa7cf485b41edfc99ff5b5
Author: Richard Holme <richard.holme@arris.com>
Date:   Thu Mar 21 12:07:03 2019 +0000

    Updated gitignore file

commit c2469dcd114c5b4bd86ce060676a7b851aaa3bb7
Author: Richard Holme <richard.holme@arris.com>
Date:   Thu Mar 21 11:53:10 2019 +0000

    Added gitignore file

commit e88b371439d3db040e162286d911e5079a6012c9
Author: Richard Holme <richard.holme@arris.com>
Date:   Thu Mar 21 11:51:53 2019 +0000

    Fixing all text files to permissions 0644

commit cae9c7d1f8a29ee3acd7c14b955f02eed7944438
Author: Richard Holme <richard.holme@arris.com>
Date:   Thu Mar 21 11:34:16 2019 +0000

    Changed executable name to match repository name